# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWsNET1y35QXG6s2Jyz9TjthqJ2nwWAc
"""

import cv2

# ============================================
# Install and import required libraries
# ============================================

# OpenCV already exists in Colab, but we import it
import cv2
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

from google.colab import files

# ============================================
# Upload MRI image
# ============================================

print(">>> Please upload your MRI image file (.jpg / .jpeg / .png)")

uploaded = files.upload()

# Getting file name
for name in uploaded.keys():
    filename = name

    print("Image uploaded successfully:", filename)

# ============================================
# Reading image using OpenCV
# ============================================

img = cv2.imread(filename)

if img is None:
    raise ValueError("Image not loaded! Check file format or upload again.")

    # Convert BGR to RGB for correct display
    rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.imshow(rgb)
    plt.title("Original MRI Image")
    plt.axis("off")
    plt.show()

# ============================================
# Converting to grayscale
# ============================================

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

plt.imshow(gray, cmap='gray')
plt.title("Grayscale MRI Image")
plt.axis("off")
plt.show()

# ============================================
# Calculating histogram of original grayscale image
# ============================================

hist_original = cv2.calcHist([gray], [0], None, [256], [0,256])

plt.figure(figsize=(6,4))
plt.plot(hist_original)
plt.title("Histogram - Original Grayscale")
plt.xlabel("Intensity")
plt.ylabel("Pixel Count")
plt.show()

# ============================================
# Applying Histogram Equalization
# ============================================

equalized = cv2.equalizeHist(gray)

plt.imshow(equalized, cmap='gray')
plt.title("Equalized MRI Image")
plt.axis("off")
plt.show()

# ============================================
# Histogram of equalized image
# ============================================

hist_eq = cv2.calcHist([equalized], [0], None, [256], [0,256])

plt.figure(figsize=(6,4))
plt.plot(hist_eq)
plt.title("Histogram - After Equalization")
plt.xlabel("Intensity")
plt.ylabel("Pixel Count")
plt.show()

# ============================================
# Showing sample pixel values (data)
# ============================================

print("===== Sample grayscale values (first 5x5 pixels) =====")
print(gray[:5, :5])

print("\n===== Sample equalized values (first 5x5 pixels) =====")
print(equalized[:5, :5])